<a href="https://colab.research.google.com/github/Prattoypaul/myml/blob/main/iriscross.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
from sklearn.datasets import load_iris
iris=load_iris()

In [4]:
from sklearn.model_selection import cross_val_score

In [5]:
from sklearn.linear_model import LogisticRegression

In [6]:
from sklearn.ensemble import RandomForestClassifier

In [7]:
from sklearn.svm import SVC

In [8]:
cross_val_score(LogisticRegression(),iris.data,iris.target)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [9]:
cross_val_score(RandomForestClassifier(),iris.data,iris.target)

array([0.96666667, 0.96666667, 0.93333333, 0.93333333, 1.        ])

In [10]:
cross_val_score(SVC(),iris.data,iris.target)

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
xtrain,xtest,ytrain,ytest=train_test_split(iris.data,iris.target,test_size=.2)

In [13]:
from sklearn.model_selection import KFold

In [25]:
kf=KFold(n_splits=5)

In [15]:
def get_score(model,xtrain,xtest,ytrain,ytest):
  model.fit(xtrain,ytrain)
  return model.score(xtest,ytest)

In [27]:
score_l=[]
score_r=[]
score_s=[]
for train_index,test_index in kf.split(iris.data):
  xtrain,xtest,ytrain,ytest=iris.data[train_index],iris.data[test_index], \
                            iris.target[train_index],iris.target[test_index]
  score_l.append(get_score(LogisticRegression(),xtrain,xtest,ytrain,ytest))
  score_r.append(get_score(RandomForestClassifier(),xtrain,xtest,ytrain,ytest))
  score_s.append(get_score(SVC(),xtrain,xtest,ytrain,ytest))

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


In [28]:
score_l

[1.0, 1.0, 0.8666666666666667, 0.9333333333333333, 0.8333333333333334]

In [29]:
score_r

[1.0, 1.0, 0.8666666666666667, 0.9333333333333333, 0.7666666666666667]

In [30]:
score_s

[1.0, 1.0, 0.8333333333333334, 0.9333333333333333, 0.7]