<a href="https://colab.research.google.com/github/Prattoypaul/myml/blob/main/kfold.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd


In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

In [ ]:
lr=LogisticRegression()
rfc=RandomForestClassifier()

In [ ]:
from sklearn.datasets import load_digits

In [ ]:
dta=load_digits()

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
xtrain,xtest,ytrain,ytest=train_test_split(dta.data,dta.target,test_size=.3)

In [ ]:
xtrain.shape

(1257, 64)

In [ ]:
from sklearn.model_selection import StratifiedKFold

In [ ]:
from sklearn.model_selection import KFold

In [30]:
kf=KFold(n_splits=3)

In [ ]:
skf=StratifiedKFold(n_splits=5)

In [26]:
def get_score(model,xtrain,xtest,ytrain,ytest):
  model.fit(xtrain,ytrain)
  return model.score(xtest,ytest)

In [37]:
score_lr=[]
score_rcf=[]
for train_index,test_index in kf.split(dta.data):
  xtrain,xtest,ytrain,ytest=dta.data[train_index],dta.data[test_index], \
                                    dta.target[train_index],dta.target[test_index]

  score_lr.append(get_score(LogisticRegression(),xtrain,xtest,ytrain,ytest))
  score_rcf.append(get_score(RandomForestClassifier(n_estimators=100),xtrain,xtest,ytrain,ytest))

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


In [38]:
score_lr

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [39]:
score_rcf

[0.9365609348914858, 0.9499165275459098, 0.9148580968280468]

In [40]:
from sklearn.model_selection import cross_val_score

In [41]:
cross_val_score(lr,dta.data,dta.target)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [43]:
cross_val_score(RandomForestClassifier(n_estimators=50),dta.data,dta.target)

array([0.93611111, 0.91388889, 0.95264624, 0.94986072, 0.93871866])

In [44]:
cross_val_score(RandomForestClassifier(n_estimators=100),dta.data,dta.target)

array([0.925     , 0.92222222, 0.96657382, 0.9637883 , 0.9275766 ])